# https://github.com/renoki-co/laravel-docker-base/actions
FROM renokico/laravel-base:1.0.0-8.0-fpm-alpine

COPY . /var/www/html

RUN mkdir -p /var/www/html/storage/logs/ && \
    chown -R www-data:www-data /var/www/html

WORKDIR /var/www/html
