# https://github.com/renoki-co/laravel-docker-base
FROM quay.io/renokico/laravel-base:worker-1.3-8.1-cli-alpine

COPY . /var/www/html

RUN mkdir -p /var/www/html/storage/logs/ && \
    chown -R www-data:www-data /var/www/html && \
    rm -rf tests/ .git/ .github/ *.md && \
    rm -rf vendor/*/test/ vendor/*/tests/*

WORKDIR /var/www/html

ENTRYPOINT ["php", "-a"]
